#!/bin/bash
unset HOSTFILE;
unset MAC;
unset MACS;
unset HOST;
unset HOSTS;
unset IFC;
source /var/lib/pmon2/general;
source /etc/pmon2/pmon2.conf
MACS=();
c=1;
if [ ! -d "/tmp/pmon" ]; then
	mkdir /tmp/pmon
fi
# echo "{" >> $HOSTS;

sqlite3 $DB "SELECT ip FROM targets" | while read -r ip; do
	echo $ip
	pingHost $ip $c
	let c=c+1;
done
php /var/lib/pmon2/GUI/artisan serve --host 0.0.0.0  --port 7000
echo $! >> /var/run/pmond.pids
# while read -r line; do
# 	declare -A HOSTDATA;
# 	if [[ ! $line ]] || [[ $line =~ '#' ]]; then
# 		continue;
# 	fi
# 	if [[ $line  =~ 'M-' ]]; then
# 		scan=$(arp-scan -l)
# 		MAC=${line:2};
# 		isMac "$MAC" || { invalidmacMsg "$MAC" && exit 2; }
# 		HOST_=$(macHaveIp "$MAC") || ipNotFoundMsg $MAC;
# 		HOSTDATA[IP]="$HOST_"
# 		HOSTDATA[mac]="$MAC";
# 		HOSTDATA[host]="HOST$c";
# 		HOSTDATA[domain]=""
# 		echo $HOST_
# 		pingHost $HOST_ $c
# 		echo "	\"HOST$c\":{ 
# 		\"HOST\":\"${HOSTDATA[host]}\",
# 		\"IP\":\"${HOSTDATA[IP]}\",
# 		\"DOMAIN\":\"${HOSTDATA[domain]}\",
# 		\"MAC\":\"${HOSTDATA[mac]}\",
# 		\"PINGPID\":\"${HOSTDATA[PINGPID]}\"
# 	}," >> $HOSTS;
# 		unset HOSTDATA
# 		let c=c+1
# 		continue;
# 	fi
# 	dest=$line;
# 	HOSTDATA[mac]=""
# 	if isIp $dest; then
# 		HOSTDATA[host]="HOST$c";  
# 		HOSTDATA[IP]=$dest;
# 		HOSTDATA[domain]=""
# 	else
# 		ip=$(nslookup $dest)
# 		ip=($ip)
# 		HOSTDATA[host]="HOST$c";  
# 		HOSTDATA[IP]="${ip[9]}"
# 		HOSTDATA[domain]="$dest"
# 	fi
# 	pingHost $dest $c;
# 	echo "	\"HOST$c\":{ 
# 		\"HOST\":\"${HOSTDATA[host]}\",
# 		\"IP\":\"${HOSTDATA[IP]}\",
# 		\"DOMAIN\":\"${HOSTDATA[domain]}\",
# 		\"MAC\":\"${HOSTDATA[mac]}\",
# 		\"PINGPID\":\"${HOSTDATA[PINGPID]}\"
# 	}," >> $HOSTS;
# 	unset HOSTDATA
# 	let c=c+1
# done < $HOSTSFILE;
# sed -i '$ s/.$//' $HOSTS;
# echo "}" >> $HOSTS;
#listen

