#!/bin/bash
source /var/lib/pmon2/pinghost
source /var/lib/pmon2/messages


#######################
#      FUNCTIONS      #
#######################
function isRoot() {
	[ "$EUID" -ne 0 ] && norootMsg;
}

function isIfc() {
	local ifc="$1";
	ifconfig "$ifc" > /dev/null 2>&1
	if [ "$?" == 1 ]; then
		echo -e "${ifc}: ${NoIfc_msg}";
		return 1;
	else
		return 0;
	fi
}
function isMac() { #valid mac?
	echo "$1" | egrep "^^([a-fA-F0-9]{2}:){5}([a-fA-F0-9]{2})$"  > /dev/null
	[ "$?" == 0 ] || return 1;
}
function isIp() { 
	if [[ $1 =~ ^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
		return 0
	else
		return 1
	fi
}
function macHaveIp() {
	local ip=$(echo "$scan" | grep "$1" | awk '{print $1}');
	local ip_comp=$(echo "$scan" | grep "$1" | awk '{print $1}' | wc -l);
	if  [ $ip_comp == 0 ]; then #Not in arp table
		return 2;
	fi
		echo $ip;
}
function keyEventListener() {
	while true; do
		read -rsn1 option;
		if [[ "$option" == "" ]] || [[ "$option" == "q" ]]; then
			kill "${pingpids[@]}";
			exit 0;
		elif [[ "$option" == "l" ]]; then
			tmux new-session -d -s pmon
			tmux send-keys "source pmon_functions.sh" C-m
			tmux send-keys "vieLog"
			tmux attach-session -t pmon
		fi
	done
}