#!/bin/bash

function dataJSON() {
	host=$1
	hostJson="/tmp/pmon/${host}.json";
	echo "{ 
		\"TIME\":\"${PTIME}\",
		\"TTL\":\"${PTTL}\",
		\"ICMP\":\"${PICMP}\",
		\"PROBLEMS\":\"${PROBLEMS}\",
		\"STATE\":\"${STATE}\"
	}" > $hostJson;
}
function downJSON() {
	host=$1
	hostJson="/tmp/pmon/${host}.json";
	echo "{ 
		\"TIME\":\"\",
		\"TTL\":\"\",
		\"ICMP\":\"\",
		\"PROBLEMS\":\"\",
		\"STATE\":\"DOWN\"
	}" > $hostJson;
}
function inestableJSON() {
	host=$1
	hostJson="/tmp/pmon/${host}.json";
	echo "{ 
		\"TIME\":\"${PTIME}\",
		\"TTL\":\"${PTTL}\",
		\"ICMP\":\"${PICMP}\",
		\"PROBLEMS\":\"${PROBLEMS}\",
		\"STATE\":\"INESTABLE\"
	}" > $hostJson;
}